### ISSUE TITLE
Why isn't this module more famous?  Or, can I use it in a production environment?

### ISSUE THREAD

**Issue by mercmobily** [rafasofizada/pechkin#3]
I am growing worried about Multer. I am not sure they are actually actively looking after it.
I found this, and it seems to be a perfect fit for me.
Why isn't everybody jumping ship and use this one instead...?

On a more practical note, do you recommend this in production?

**Comment by rafasofizada** [comment]
Hi Tony! I'm glad you found the package useful.

Multer serves the case of uploading simple forms with not too much control over how and when files are processed pretty well. Having read throught the entire source code and Github issues of Multer, there don't seem to be any glaring burning problems with the package, hence the lack of ongoing maintenance.

I'm obviously biased here, but sure you can use this in production -- it's still used at a project at my previous job that handles plenty of file uploads in large forms with singular files, file arrays, ordinary fields, etc.

I'm also in the process of adding some new features and publishing a v2, so I'm actively looking out for any bugs. The previous, pretty serious, issue #2 was resolved within 1 day.

**Comment by mercmobily** [comment]
Sweet. Thank you for your answer. When are you planning on releasing V2?

**Comment by mercmobily** [comment]
Sorry, maybe my last question sounded like I was trying to hurry you...
I really only wanted to know a rough estimate of when you might release version 2 so that I time my own project properly


(I realise Multer is great etc., but because of it, we are effectively stuck with Node 12 (!) since  Multer uses a very old version of temp-fs with huge problems which fails to load attachments...)

**Comment by rafasofizada** [comment]
Hey! Sorry I was on a long New Year's break. I don't really have a roadmap right now, there's not much (IMO) to fix/add for a "v2" release. If you're using it at your company and have specific requests for the library (or something to fix in your file processing pipeline), I can help you out on a contracting basis :) Email me at rafa.sofizadeh@gmail.com

**Comment by mercmobily** [comment]
All good will make a ticked it I need to. I think this is gonna be the way we go. Thank you!

**Comment by rafasofizada** [comment]
Welcome! Hope to get to work together in the future.

**Comment by mercmobily** [comment]
Well I am switching. Multer will only work on Node 14 or lower, I created an issue there asking if it was abandoned, but at this point I don't think there is any point. I think they should put a notice in the project's page stating that it's abandonware and asking for somebody to take over. Or, even better, direct them here.

**Comment by rafasofizada** [comment]
Glad to hear that! Feel free to open any issues with functionality suggestions / bugs, or for open-ended discussions, hit me up on my email (in my profile).

**Comment by mercmobily** [comment]
I am talking to them,  they want to stick to CJS and they seem a little stuck. Shame. I am switching to pechkin... Will start sometime this month. Thank you!
