### ISSUE TITLE
Multiple file uploads

### ISSUE THREAD

**Issue by tzwel** [rafasofizada/pechkin#5]
Does this library support multiple file uploads? From what I see in the docs, there exsists an `maxFileCountPerField` option so it certainly is. Not sure if this is my implementation problem (almost certainly is) or a bug in the lib (busboy behaves the same), but I can't upload more than one file. Only one gets saved to disk, while (probably?) both get parsed.

Here's the config:
```js
pechkinFileUpload({
		maxFileByteLength: 50 * 1024 * 1024,
		maxFileCountPerField: 15,
		maxTotalFieldCount: 0,
	}
```

And the code that handles the files

```js
const files = [];
for await (const { stream, field, filename, encoding, mimeType } of req.files) {

	// ... irrevelant code here ...

	files.push({
		'submittedName': filename,
		// ... some more non relevant stuff... 
	})

	stream.pipe(fs.createWriteStream(savePath));
}

console.log(files);  // This array always contains only ONE file!

files.forEach(async file => {
	// save files to db
});
```

Am I calling everything too early? Should I use a promise? Would be great if there was an example if it's a problem in my implementation, so people won't have to ask in the future 👍

**Comment by rafasofizada** [comment]
Hey! Thanks for reporting the issue. Of course the library supports multiple file uploads, otherwise it'd be almost useless :D I suspect the actual problem is in the way you send requests from the front-end. Can I see how your request code looks like? If busboy behaves the same, it's almost certainlty something to do with your `multipart/form-data` request itself.

**Comment by tzwel** [comment]
Not a problem! It's in Svelte, however. It's nothing fancy, I let the browser do the most 
```js
async function uploadHandler(e) {
	e.preventDefault()
	const action = get(env).host + '/' + e.target.getAttribute('action')
	const formData = new FormData();
	formData.append('file', files.files[0]);
	let fetched = await fetch(action, { 
		method: 'POST',
		body: formData
	});
}
```

**Comment by tzwel** [comment]
lol I see what happens here, `[0]`. Not sure if I added this after the "bug" happened or before, will close the issue if it's on my end. That's what no sleep does to a man

**Comment by tzwel** [comment]
100% sure it's my fault but hard to pinpoint where. Sending only 1 file works, but when multiple get sent, it seems like none get parsed. No idea how to even provide a reproducible example

**Comment by tzwel** [comment]
It was actually this simple. Shame on me
```js
for (const file of files.files) {
	formData.append('file', file);
}
```
Thank you for your great library, it's a delight compared to other libs supposedly designed for file handling. 
If you are reading this, do you know any good resources to learn how piping works? I'm trying to generate thumbnails from the stream, but failing miserably. Is the optimal solution to just write the file to disk and read it again?
